In [14]:
import pandas as pd

In [15]:
covid_data = pd.read_csv('owid-covid-data.csv')

In [16]:
covid_data.head(5)

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand
0,AFG,Asia,Afghanistan,2019-12-31,0.0,0.0,0.0,0.0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
1,AFG,Asia,Afghanistan,2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
2,AFG,Asia,Afghanistan,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
3,AFG,Asia,Afghanistan,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
4,AFG,Asia,Afghanistan,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5

In [17]:
covid_data.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'total_deaths', 'new_deaths', 'total_cases_per_million',
       'new_cases_per_million', 'total_deaths_per_million',
       'new_deaths_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'tests_units',
       'stringency_index', 'population', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cvd_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand'],
      dtype='object')

In [18]:
covid_data = covid_data[covid_data['continent']=='Europe']

In [19]:
covid_data = covid_data[['location', 'date', 'total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'population', 'population_density', 'median_age', 'gdp_per_capita', 'cvd_death_rate']]

In [20]:
dem_data = pd.read_csv('demographic-data.csv', sep=';')

In [21]:
dem_data.head(5)

,Country,Overall Life Expectancy,Female Life Expectancy,Male Life Expectancy,Number of doctors per 1000 people
0,Japan,84.5,87.5,81.1,"2,30765"
1,Singapore,83.8,85.8,81.5,"1,8461"
2,Italy,83.6,85.5,81.7,"3,9044"
3,Spain,83.4,86.1,80.7,"3,1541"
4,Switzerland,83.4,85.3,81.1,"4,0737"

In [22]:
data = pd.merge(covid_data, dem_data, left_on="location", right_on="Country")

In [27]:
data.to_csv('covid_merged_data_clean.csv')